import './globals.css'
import type { Metadata } from 'next'
import { Inter,Lexend_Exa,Outfit } from 'next/font/google'
const outfit = Outfit({ subsets: ['latin'] })
const lexend = Lexend_Exa({subsets:['latin']})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${outfit.className} ${lexend.className}`}>{children}</body>
    </html>
  )
}
