import Sidebar from './components/client/Sidebar'
import { outfit } from './fonts'
import './globals.css'
import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'MAGNIMUS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <main className="h-[100vh] flex overflow-hidden max-sm:flex-col max-sm:overflow-hidden">
            <Sidebar />
            {children}
            <div className="min-h-[100px] w-full bg-[#ADD2B5] hidden max-sm:flex items-center justify-between px-5 font-medium"><span>Lorem</span><span>Ipsum</span></div>
        </main>
      </body>
    </html>
  )
}
